### ISSUE TITLE
Backend is listed in docker-compose, but readme says it's not

### ISSUE THREAD

**Issue by ffissore** [balena-io/services-masterclass#7]
In section [3.1 Multicontainer docker-compose Manifest](https://github.com/balena-io-projects/services-masterclass#31-multicontainer-docker-compose-manifest), readme says 
> but is not used as the docker-compose manifest does not define another service that uses it

This is not true, as docker-compose.yml [features the backend](https://github.com/balena-io-projects/services-masterclass/blob/master/multicontainer-app/docker-compose.yml#L6), but with no exposed ports

Should we change the readme specifying that backend is there but not accessible/its port not exposed, or should we remove the backend service from docker-compose.yml?

**Comment by hedss** [comment]
`docker-compose.yml` no longer includes the `backend` service, so the reader can add it as part of the exercise.
